services:
  postgres:
    image: postgres:16
    container_name: forgeorder-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: forgeorder
      POSTGRES_USER: forgeorder_user
      POSTGRES_PASSWORD: forgeorder_pass
    ports:
      - "5433:5432"
    volumes:
      - forgeorder-postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: forgeorder-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: forgeorder_user
      RABBITMQ_DEFAULT_PASS: forgeorder_pass

volumes:
  forgeorder-postgres-data: