package com.sagar.forgeorder.orders.domain;

public enum OrderStatus {
    DRAFT,
    CREATED,
    INVENTORY_RESERVATION_PENDING,
    INVENTORY_RESERVED,
    INVENTORY_UNAVAILABLE,
    PAYMENT_PENDING,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    PAYMENT_STATUS_UNKNOWN,
    RECONCILIATION_REQUIRED,
    INVENTORY_RELEASE_PENDING,
    CANCELLATION_REQUESTED,
    CANCELLED,
    CONFIRMED,
    FULFILLED,
    REFUND_PENDING,
    REFUNDED
}